#!/usr/bin/env node
/**
 * Regenerate the committed snapshot from the publishers' APIs.
 *
 *   npm run refresh-data
 *
 * Writes src/data/snapshots/generated.json. Every entry it writes supersedes
 * the hand-transcribed literal in src/data/series/*.ts and clears that
 * series' "not yet machine-verified" label in the UI.
 *
 * The script is deliberately conservative: a series that fails to fetch keeps
 * whatever was in the file before, so a transient outage can never blank out
 * the site's fallback data.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { MANIFEST } from './manifest.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(here, '../src/data/snapshots/generated.json')
const WORLD_BANK = 'https://api.worldbank.org/v2'
const TIMEOUT_MS = 20000
const RETRIES = 3

function log(...args) {
  process.stdout.write(`${args.join(' ')}\n`)
}

async function getJson(url) {
  let lastError
  for (let attempt = 1; attempt <= RETRIES; attempt += 1) {
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS)
    try {
      const res = await fetch(url, {
        signal: controller.signal,
        headers: { accept: 'application/json', 'user-agent': 'india-in-data/refresh' },
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      return await res.json()
    } catch (err) {
      lastError = err
      // Exponential backoff: 1s, 2s, 4s.
      if (attempt < RETRIES) await new Promise((r) => setTimeout(r, 2 ** (attempt - 1) * 1000))
    } finally {
      clearTimeout(timer)
    }
  }
  throw lastError
}

function worldBankUrl(entry, country) {
  const to = new Date().getFullYear()
  return `${WORLD_BANK}/country/${country}/indicator/${entry.indicator}?format=json&per_page=800&date=${entry.from}:${to}`
}

async function fetchWorldBank(entry) {
  const country = entry.country ?? 'IND'
  const url = worldBankUrl(entry, country)
  const json = await getJson(url)
  if (!Array.isArray(json) || !Array.isArray(json[1])) throw new Error('unexpected payload')
  const scale = entry.scale ?? 1
  const points = json[1]
    .filter((r) => r && typeof r.date === 'string')
    .map((r) => ({ x: Number(r.date), y: typeof r.value === 'number' ? r.value * scale : null }))
    .filter((p) => Number.isFinite(p.x))
    .sort((a, b) => a.x - b.x)
  if (!points.some((p) => p.y !== null)) throw new Error('no observations')
  return { points, endpoint: url }
}

async function fetchWorldBankShare(entry) {
  const to = new Date().getFullYear()
  const url = `${WORLD_BANK}/country/IND;WLD/indicator/${entry.indicator}?format=json&per_page=1200&date=${entry.from}:${to}`
  const json = await getJson(url)
  if (!Array.isArray(json) || !Array.isArray(json[1])) throw new Error('unexpected payload')
  const india = new Map()
  const world = new Map()
  for (const r of json[1]) {
    if (!r?.date || typeof r.value !== 'number') continue
    if (r.countryiso3code === 'IND') india.set(r.date, r.value)
    else if (r.countryiso3code === 'WLD') world.set(r.date, r.value)
  }
  const points = [...india.keys()]
    .map((year) => {
      const w = world.get(year)
      const i = india.get(year)
      return { x: Number(year), y: w && i ? (i / w) * 100 : null }
    })
    .filter((p) => Number.isFinite(p.x))
    .sort((a, b) => a.x - b.x)
  if (!points.some((p) => p.y !== null)) throw new Error('no observations')
  return { points, endpoint: url }
}

const FETCHERS = {
  worldbank: fetchWorldBank,
  'worldbank-share': fetchWorldBankShare,
}

async function main() {
  let existing = { generatedAt: null, series: {} }
  try {
    existing = JSON.parse(await readFile(OUT, 'utf8'))
  } catch {
    /* first run */
  }

  const series = { ...existing.series }
  const failures = []
  const now = new Date().toISOString()

  for (const entry of MANIFEST) {
    const fetcher = FETCHERS[entry.kind]
    if (!fetcher) {
      failures.push(`${entry.id}: unknown provider kind "${entry.kind}"`)
      continue
    }
    try {
      const { points, endpoint } = await fetcher(entry)
      series[entry.id] = { points, fetchedAt: now, endpoint }
      log(`  ok    ${entry.id} (${points.filter((p) => p.y !== null).length} observations)`)
    } catch (err) {
      failures.push(`${entry.id}: ${err instanceof Error ? err.message : String(err)}`)
      log(`  FAIL  ${entry.id} — ${err instanceof Error ? err.message : err}`)
    }
  }

  const payload = {
    generatedAt: now,
    note: 'Generated by scripts/refresh-data.mjs. Do not edit by hand — rerun `npm run refresh-data`.',
    series,
  }
  await writeFile(OUT, `${JSON.stringify(payload, null, 2)}\n`, 'utf8')

  const succeeded = MANIFEST.length - failures.length
  log(`\n${succeeded}/${MANIFEST.length} series refreshed into src/data/snapshots/generated.json`)

  if (failures.length) {
    log(`\n${failures.length} failed:`)
    failures.forEach((f) => log(`  - ${f}`))
    // Partial success still writes the file; a total failure is an error.
    if (succeeded === 0) {
      log('\nNothing was refreshed. Leaving the previous snapshot in place.')
      process.exit(1)
    }
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
