/* ==========================================================================
   The data contract.

   Every number rendered anywhere on this site travels through these types,
   which is what makes the sourcing claim enforceable rather than decorative:
   a series cannot be plotted unless it names a source in the register, states
   the unit it is measured in, and carries a committed snapshot to fall back
   to when the live call fails.
   ========================================================================== */

/** How the numbers currently on screen were obtained. */
export type Provenance =
  /** Read from the project's Supabase catalogue — the canonical store. */
  | 'database'
  /** Fetched from the publisher's API in this browser, just now. */
  | 'live'
  /** Fetched from the publisher's API earlier in this browser, still inside its TTL. */
  | 'live-cached'
  /** The publisher exposes no machine API: values are transcribed from a cited release. */
  | 'curated'
  /** The live call failed or was blocked; the committed snapshot is being shown. */
  | 'snapshot'
  | 'loading'

export type Unit =
  | 'usd'
  | 'usd-billion'
  | 'usd-trillion'
  | 'inr'
  | 'inr-crore'
  | 'inr-lakh-crore'
  | 'percent'
  | 'count'
  | 'million'
  | 'billion'
  | 'index'
  | 'rank'
  | 'per-lakh'
  | 'per-1000'
  | 'years'
  | 'usd-per-gb'
  | 'km'
  | 'ratio'

/** A single observation. `x` is a year, a fiscal-year label, or a category. */
export interface Point {
  x: string | number
  y: number | null
  /** Optional per-point footnote (revision, break in series, provisional). */
  flag?: string
}

/** What a live provider must return. */
export type LiveFetcher = (signal: AbortSignal) => Promise<Point[]>

export interface LiveSpec {
  /** Human-readable description of the call, shown in the methodology page. */
  endpoint: string
  fetch: LiveFetcher
}

export interface SeriesSpec {
  id: string
  /** Legend / tooltip label. */
  label: string
  unit: Unit
  /** Key into the source register. Enforced at build time by `SourceId`. */
  sourceId: SourceId
  /** Optional second source, when a series splices two publishers. */
  alsoSourceIds?: SourceId[]
  /** Live retrieval. Omit for series no publisher exposes as an API. */
  live?: LiveSpec
  /** Committed fallback, always present. */
  snapshot: Point[]
  /** The date the snapshot values were transcribed or last regenerated. */
  snapshotAsOf: string
  /** How many decimal places to show. */
  precision?: number
  /** Series-level caveat, rendered under the figure. */
  note?: string
  /**
   * Set when a snapshot value was transcribed by hand from a publication and
   * has not yet been re-generated by `npm run refresh-data`. Surfaced in the
   * UI so a reader is never told a number is verified when it is not.
   */
  unverified?: boolean
}

export interface LoadedSeries {
  spec: SeriesSpec
  points: Point[]
  provenance: Provenance
  /** When the live values were retrieved. */
  fetchedAt?: string
  /** Why the live call failed, when it did. */
  error?: string
}

/* -- the source register -------------------------------------------------- */

export type SourceCategory =
  | 'Government of India'
  | 'Reserve Bank of India'
  | 'Multilateral'
  | 'Research institute'
  | 'Industry body'

export type AccessMode =
  /** Open API, queried directly from the reader's browser. */
  | 'api'
  /** Machine-readable bulk file (CSV/JSON) published on a stable URL. */
  | 'bulk'
  /** PDF or HTML release; values are transcribed and cited. */
  | 'publication'

export interface Source {
  id: string
  name: string
  publisher: string
  url: string
  /** What the source is and what it is good for. */
  description: string
  category: SourceCategory
  access: AccessMode
  /** How often the publisher updates it. */
  cadence: string
  /** Licence or terms, as published. */
  licence: string
  /** Known limitations a reader should carry into the charts. */
  caveat?: string
}

/** Narrowed at module load in `sources.ts` so a typo cannot ship. */
export type SourceId = string
